Mahasiswa_New/Models/JurusanModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mahasiswa_New.Models
{
    public class JurusanModel
    {
        public string idJurusan {get; set;}

        public string jurusan {get; set;}
    }
}

Mahasiswa_New/Models/MahasiswaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mahasiswa_New.Models
{
    public class MahasiswaModel
    {
        public int Id { get; set; }

        public string NPM { get; set; }

        public string Nama { get; set; }

        public string JK { get; set; }

        public string idJurusan { get; set; }

        public string Jurusan { get; set; }

        public string Alamat { get; set; }

        public string TglLahir { get; set; }

        public string Email { get; set; }
    }
}

Mahasiswa_New/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mahasiswa_New.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        //komen lagi
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Mahasiswa_New/Controllers/JurusanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mahasiswa_New.Services;
using Mahasiswa_New.Models;

namespace Mahasiswa_New.Controllers
{
    public class JurusanController : Controller
    {
        // GET: Jurusan
        public ActionResult Index()
        {
            GetListJurusan();
            return View();
        }

        public ActionResult GetListJurusan()
        {
            JurusanService service = new JurusanService();
            ViewData["ListJurusan"] = service.GetListJurusan();
            return PartialView("Partial/_ListJurusan");
        }

        public bool ValidasiCreate(string Id)
        {
            JurusanService service = new JurusanService();
            bool result = service.IsDataExist(Id);
            return (result);
        }

        public ActionResult Create(JurusanModel model)
        {
            JurusanService service = new JurusanService();
            int hasil = service.SimpanJurusan(model);
            if (hasil != -1)
            {
                return GetListJurusan();
            }
            return null;
        }

        public ActionResult Edit(JurusanModel model)
        {
            JurusanService service = new JurusanService();
            int hasil = service.UpdateJurusan(model);
            if (hasil != -1)
            {
                return GetListJurusan();
            }
            return null;
        }

        public ActionResult Deletet(string Id)
        {
            JurusanService service = new JurusanService();
            int hasil = service.DeleteJurusan(Id);
            if (hasil != -1)
            {
                return GetListJurusan();
            }
            return null;
        }
    }
}

Mahasiswa_New/Controllers/MahasiswaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mahasiswa_New.Services;
using Mahasiswa_New.Models;

namespace Mahasiswa_New.Controllers
{
    public class MahasiswaController : Controller
        
    {
        MahasiswaService Mahasiswa;


        // GET: Mahasiswa
        public ActionResult Index()
        {
            Mahasiswa = new MahasiswaService();
            var result = Mahasiswa.GetListMahasiswa();
            return View(result);
        }

        // GET: Mahasiswa/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Mahasiswa/Create
        public ActionResult Create()
        {
            Mahasiswa = new MahasiswaService();
            ViewData["jurusan"] = Mahasiswa.GetJurusan();
            return View();
        }

        // POST: Mahasiswa/Create
        [HttpPost]
        public ActionResult Create(MahasiswaModel model)
        {
            try
            {
                Mahasiswa = new MahasiswaService();
                bool IsdataExist = Mahasiswa.IsDataExist(model.NPM);
                if (IsdataExist)
                {
                    return Json(new { success = false, message = "Data already exist" }, JsonRequestBehavior.AllowGet);
                }
                Mahasiswa.SimpanMahasiswa(model);
                return Json(new { success = true, message = "Data Saved Successfully" }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new { success = false, message = "Data Saved failed" }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Mahasiswa/Edit/5
        public ActionResult Edit(string id)
        {
            Mahasiswa = new MahasiswaService();
            ViewData["jurusan"] = Mahasiswa.GetJurusan();
            return View(Mahasiswa.GetListMahasiswaById(id));
        }

        // POST: Mahasiswa/Edit/5
        [HttpPost]
        public ActionResult Edit(MahasiswaModel model)
        {
            try
            {
                // TODO: Add update logic here
                Mahasiswa = new MahasiswaService();

                Mahasiswa.UpdateMahasiswa(model);
                return Json(new { success = true, message = "Data Update Successfully" }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new { success = false, message = "Save data failed" }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Mahasiswa/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Mahasiswa/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Mahasiswa_New/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Mahasiswa_New/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Mahasiswa_New/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            toastr.success("Testing");
        });

        toastr.options = {
            "positionClass": "toast-top-center",
            "timeOut": "1000",
            "preventDuplicates": true
        }

    </script>
    }

Mahasiswa_New/Views/Jurusan/Index.cshtml
@using Mahasiswa_New.Models
@{
    ViewBag.Title = "JURUSAN";
}
<hr />
<div id="MainForm">
    <div id="tablegrid">
        @Html.Partial("Partial/_ListJurusan")
    </div>
</div>
<div class="modal fade" id="_popup" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content panel panel-primary">
            <div class="panel-heading">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title" id="_title"></h2>
            </div>
            <div class="modal-body">
                <h4 style="color:red;" class="hidden" id="_delConfirm"> Are Your sure delete this data?</h4>
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="col-sm-3 col-md-4 control-label text-muted" style="text-align:left;">Id Jurusan</label>
                        <label class="col-sm-1 col-md-1 control-label text-muted">:</label>
                        <div class="col-sm-8 col-md-7">
                            <input id="_inputState" class="form-control hidden" />
                            <input id="_id" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-4 control-label text-muted" style="text-align:left;">Jurusan</label>
                        <label class="col-sm-1 col-md-1 control-label text-muted">:</label>
                        <div class="col-sm-8 col-md-7">
                            <input id="_jurusan" class="form-control" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="_saveBtn" class="btn btn-primary" onclick="return ProsesData()"><span class="bold fa fa-save"></span>&nbsp;&nbsp;Save</button>
                <button type="button" class="btn btn-default" data-dismiss="modal"><span class="bold fa fa-save"></span>&nbsp;&nbsp;Cancel</button>
            </div>
        </div>
    </div>
</div>
@section scripts {
    <script>
        $(document).ready(function () {
            DataTable();
        });
        var Id;
        var Jurusan;

        function Init() {
            Id = "";
            Jurusan = "";
        }

        function DataTable() {
            $('#table').DataTable({
                "destroy" : true,
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false
            });
        }

        toastr.options = {
            "positionClass": "toast-top-center",
            "timeOut": "1000",
            "preventDuplicates": true,
        }

        function CreatePopup() {
            Init();
            $("#_popup").modal({ backdrop: 'static' });
            $("#_title").text("Create Jurusan");
            $("#_inputState").val("Create");
            $("#_id").val("");
            $("#_jurusan").val("");

            $("#_id").removeAttr("disabled");
            $("#_jurusan").removeAttr("disabled");
            $("#_delConfirm").addClass("hidden");
            $("#_saveBtn").removeClass("hidden");
            $("#_id").focus();
        }

        function EditPopUp(data) {
            Init();
            $("#_popup").modal({ backdrop: 'static' });
            $("#_title").text("Edit Jurusan");
            var Id = data.closest("tr").find("._id").text();
            var Jurusan = data.closest("tr").find("._jurusan").text();
            $("#_inputState").val("Edit");
            $("#_id").val(Id);
            $("#_jurusan").val(Jurusan);
            $("#_jurusan").focus();

            $("#_id").attr("disabled", "disabled");
            $("#_jurusan").removeAttr("disabled", "disabled");
            $("#_delConfirm").addClass("hidden");
            $("#_saveBtn").removeClass("hidden");
        }

        function DeletePopUp(data) {
            Init();
            $("#_popup").modal({ backdrop: 'static' });
            $("#_title").text("Delete Jurusan");
            var Id = data.closest("tr").find("._id").text();
            var Jurusan = data.closest("tr").find("._jurusan").text();
            $("#_inputState").val("Delete");
            $("#_id").val(Id);
            $("#_jurusan").val(Jurusan);
            $("#_jurusan").focus();

            $("#_id").attr("disabled", "disabled");
            $("#_jurusan").attr("disabled", "disabled");
            $("#_delConfirm").removeClass("hidden");
            $("#_saveBtn").removeClass("hidden");
        }

        function DetailPopUp(data) {
            Init();
            $("#_popup").modal({ backdrop: 'static' });
            $("#_title").text("Detail Jurusan");
            var Id = data.closest("tr").find("._id").text();
            var Jurusan = data.closest("tr").find("._jurusan").text();
            $("#_inputState").val("Detail");
            $("#_id").val(Id);
            $("#_jurusan").val(Jurusan);
            $("#_jurusan").focus();


            $("#_id").attr("disabled", "disabled");
            $("#_jurusan").attr("disabled", "disabled");
            $("#_delConfirm").addClass("hidden");
            $("#_saveBtn").addClass("hidden");
        }

        function ProsesData() {
            var InputState = $('#_inputState').val();
            Id = $("#_id").val();
            Jurusan = $('#_jurusan').val();
            if (InputState == "Create") {
                if (Id == "") {
                    $("#_id").focus();
                    alert("Id tidak boleh kosong");
                    toastr.warning("Id tidak boleh kosong")
                } else {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("ValidasiCreate", "Jurusan")',
                        data: {
                            Id: Id
                        },
                        complete: function (result) {
                            if (result.responseText == "true") {
                                toastr.warning('data sudah ada mohon periksa ulang')
                                $("#_id").focus();
                            }
                            else {
                                Create();
                                Init();
                            }
                        }
                    });
                }
            } else if (InputState == "Edit") {
                Edit();
                Init();
            } else if (InputState == "Delete") {
                Delete();
                Init();
            }
        }

        function Create() {
            if (Jurusan == "") {
                $("#_jurusan").focus();
                toastr.warning("Jurusan Tidak Boleh Kosong")
            }
            else {
                var jur = {
                    idJurusan: Id,
                    jurusan: Jurusan
                }
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Create", "Jurusan")',
                    data: {
                        model: jur
                    },
                    complete: function (result) {
                        $("#tablegrid").html(result.responseText);
                        toastr.success("Simpan Data Berhasil");
                        $("#_popup").modal('hide');
                        return DataTable();
                    }
                });
            }
        }

        function Edit() {
            if (Id == "") {
                $("#_id").focus();
                toastr.warning("Tidak ada data yang diupdate")
            }
            else if (Jurusan == "") {
                $("#_jurusan").focus();
                toastr.warning("Jurusan tidak boleh kosong")   
            }else{
                var model = {
                    idJurusan: Id,
                    jurusan: Jurusan
            }
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Edit", "Jurusan")',
                    data: {
                        model: model
                    },
                    complete: function (result) {
                        $("#tablegrid").html(result.responseText);
                        toastr.success("Update Data Berhasil");
                        $("#_popup").modal('hide');
                        return DataTable();
                    }
                });
            }
        }

        function Delete() {
            if (Id == "") {
                $("#_id").focus();
                toastr.warning("Tidak ada data yang dihapus")
            }
            else {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Deletet", "Jurusan")',
                    data: {
                        Id: Id
                    },
                    complete: function (result) {
                        $("#tablegrid").html(result.responseText);
                        toastr.success("Update Data Berhasil");
                        $("#_popup").modal('hide');
                        return DataTable();
                    }
                });
            }
        }

    </script>
}

Mahasiswa_New/Views/Mahasiswa/Create.cshtml
@using Mahasiswa_New.Helpers;

@{
    ViewBag.Title = "Create";
    List<StandartComboBox> jurusan = (List<StandartComboBox>)ViewData["jurusan"];
}

<h2>Create</h2>
<hr />
<div class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-1 col-md-1 control-label text-muted" style="text-align:left;">NPM</label>
        <label class="col-sm-1 col-md-1 control-label text-muted" >:</label>
        <div class="col-sm-10 col-md-10">
            <input id="_npm" class="form-control"/>
        </div>
    </div>


    <div class="form-group">
        <label class="col-sm-1 col-md-1 control-label text-muted" style="text-align:left;">Nama</label>
        <label class="col-sm-1 col-md-1 control-label text-muted">:</label>
        <div class="col-sm-10 col-md-10">
            <input id="_nama" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-1 col-md-1 control-label text-muted" style="text-align:left;">JK</label>
        <label class="col-sm-1 col-md-1 control-label text-muted">:</label>
        <div class="col-sm-10 col-md-10">
            <select id="_jk" class="form-control" style="width:100%">
            <option value="">-- jenis Kelamin --</option>
            <option value="L">Laki - Laki</option>
            <option value="P">Perempuan</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-1 col-md-1 control-label text-muted" style="text-align:left;">Tgl lahir</label>
        <label class="col-sm-1 col-md-1 control-label text-muted">:</label>
        <div class="col-sm-10 col-md-10">
            <input id="_tgl" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-1 col-md-1 control-label text-muted" style="text-align:left;">Alamat</label>
        <label class="col-sm-1 col-md-1 control-label text-muted">:</label>
        <div class="col-sm-10 col-md-10">
            <textarea id="_alamat" rows="4" cols="50 "class="form-control"></textarea>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-1 col-md-1 control-label text-muted" style="text-align:left;">Jurusan</label>
        <label class="col-sm-1 col-md-1 control-label text-muted">:</label>
        <div class="col-sm-10 col-md-10">
            <select id="_jurusan" class="form-control" style="width:100%">
                <option value="">-- Jurusan --</option>
                @foreach (var item in jurusan)
                {
                    <option value="@item.value">@item.Text</option>
                }
            </select>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-1 col-md-1 control-label text-muted" style="text-align:left;">Email</label>
        <label class="col-sm-1 col-md-1 control-label text-muted">:</label>
        <div class="col-sm-10 col-md-10">
            <input id="_email" type="email" class="form-control" />
        </div>
    </div>
    <hr />
    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <button type="button" class="btn btn-primary" onclick="return Simpan()" style="width:100px">Simpan</button>&nbsp;
            @Html.ActionLink("Back To List", "Index", null, new { @class = "btn btn-default", @style ="width:100px"})
        </div>
    </div>
</div>
@section scripts{
    <script>
        $(document).ready(function () {
            $('#_tgl').datepicker({
                autoclose: true,
                orientation: "bottom left",
                todayHighlight: true
            });
        })

        toastr.options = {
            "positionClass": "toast-top-center",
            "timeOut": "1000",
            "preventDuplicates": true
        }
        function Simpan() {
            var npm = $("#_npm").val();
            var nama = $("#_nama").val();
            var alamat = $("#_alamat").val();
            var jurusan = $("#_jurusan").val();
            var jk = $("#_jk").val();
            var npm = $("#_npm").val();
            var tgllahir = $("#_tgl").val();
            var email = $("#_email").val();
            if (npm == "") {
                $("#_npm").focus();
                toastr.warning('NPM harus diisi')
            } else if (nama == "") {
                $("#_nama").focus();
                toastr.warning('Nama harus diisi')
            } else if (alamat == "") {
                $("#_alamat").focus();
                toastr.warning('Alamat harus diisi')
            } else if (tgllahir == "") {
                $("#_tgl").focus();
                toastr.warning('Tgl harus diisi')
            } else if (email == "") {
                $("#_email").focus();
                toastr.warning('Email harus diisi')
            } else if (jurusan == "") {
                toastr.warning('Pilih Jurusan')
            } else {
            var saveUrl = '@Url.Action("Create", "Mahasiswa")';
            var IndexUrl = '@Url.Action("Index", "Mahasiswa")';
            var model = {
                NPM: npm,
                Nama: nama,
                JK: jk,
                idJurusan: jurusan,
                Alamat: alamat,
                TglLahir: formatDate(tgllahir),
                Email: email
            };
            $.ajax({
                type: "POST",
                url: saveUrl,
                data: {model: model},
                success: function (data){
                    if (data.success) {
                        alert(data.message);
                        window.location.href = IndexUrl;

                    } else {
                        alert(data.message);
                    }
                }
            });
        }
        }
        function formatDate(date) {
            var d = new Date(date),
                month = '' + (d.getMonth() + 1),
                day = '' + d.getDate(),
                year = '' + d.getFullYear();
            if (month.length < 2) month = '0' + month;
            if (day.length < 2) day = '0' + day;

            return [year, month, day].join('-');
        }
    </script>
    }

Mahasiswa_New/Views/Mahasiswa/Edit.cshtml
@using Mahasiswa_New.Helpers;
@model List<Mahasiswa_New.Models.MahasiswaModel>


@{
    ViewBag.Title = "Edit";
    List<StandartComboBox> jurusan = (List<StandartComboBox>)ViewData["jurusan"];

    string npm = "";
    string nama = "";
    string jk = "";
    string tglLahir = "";
    string alamat = "";
    string jur = "";
    string email = "";
    foreach (var item in Model)
    {
        npm = item.NPM;
        nama = item.Nama;
        jk = item.JK;
        tglLahir = item.TglLahir;
        alamat = item.Alamat;
        jur = item.idJurusan;
        email = item.Email;
    }
}
<h2>Create</h2>
<hr />
<div class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-1 col-md-1 control-label text-muted" style="text-align:left;">NPM</label>
        <label class="col-sm-1 col-md-1 control-label text-muted ">:</label>
        <div class="col-sm-10 col-md-10">
            <input id="_npm" class="form-control" value="@npm" disabled />
            <input id="_jurusan1" class="form-control hidden" value="@jur" />
            <input id="_jk1" class="form-control hidden" value="@jk" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 col-md-1 control-label text-muted" style="text-align:left;">Nama</label>
        <label class="col-sm-1 col-md-1 control-label text-muted ">:</label>
        <div class="col-sm-10 col-md-10">
            <input id="_nama" class="form-control" value="@nama" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 col-md-1 control-label text-muted" style="text-align:left;">JK</label>
        <label class="col-sm-1 col-md-1 control-label text-muted ">:</label>
        <div class="col-sm-10 col-md-10">
            <select id="_jk" class="form-control" style="width:100%">
                <option value="">-- Jenis Kelamin --</option>
                <option value="L">Laki - Laki</option>
                <option value="P">Perempuan</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 col-md-1 control-label text-muted" style="text-align:left;">Tgl Lahir</label>
        <label class="col-sm-1 col-md-1 control-label text-muted ">:</label>
        <div class="col-sm-10 col-md-10">
            <input id="_tgl" class="form-control" value="@tglLahir" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 col-md-1 control-label text-muted" style="text-align:left;">Alamat</label>
        <label class="col-sm-1 col-md-1 control-label text-muted ">:</label>
        <div class="col-sm-10 col-md-10">
            <textarea id="_alamat" rows="4" cols="50" class="form-control">@alamat</textarea>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 col-md-1 control-label text-muted" style="text-align:left;">Jurusan</label>
        <label class="col-sm-1 col-md-1 control-label text-muted ">:</label>
        <div class="col-sm-10 col-md-10">
            <select id="_jurusan" class="form-control" style="width:100%">
                <option value="">-- Jurusan --</option>
                @foreach (var item in jurusan)
                {
                    <option value="@item.value">@item.Text</option>
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 col-md-1 control-label text-muted" style="text-align:left;">Email</label>
        <label class="col-sm-1 col-md-1 control-label text-muted ">:</label>
        <div class="col-sm-10 col-md-10">
            <input id="_email" type="email" class="form-control" value="@email" />
        </div>
    </div>
    <hr />
    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <button type="button" class="btn btn-primary" onclick="return Update()" style="width:100px">Update</button>&nbsp;
            @Html.ActionLink("Back To List", "Index", null, new { @class = "btn btn-default", @style = "width:100px" })
        </div>
    </div>
</div>
@section scripts{
    <script>
        $(document).ready(function () {
            $('#_tgl').datepicker({
                autoclose: true,
                orientation: "bottom left",
                todayHighlight: true
            });

            var jurus = $('#_jurusan1').val();
            var jk = $('#_jk1').val();
            $("#_jurusan").val(jurus);
            $("#_jk").val(jk);
        })

        toastr.options = {
            "positionClass": "toast-top-center",
            "timeOut": "1000",
            "preventDuplicates": true
        }
        function Update() {
            var npm = $("#_npm").val();
            var nama = $("#_nama").val();
            var alamat = $("#_alamat").val();
            var jurusan = $("#_jurusan").val();
            var jk = $("#_jk").val();
            var tglLahir = $("#_tgl").val();
            var email = $("#_email").val();
            if (npm == "") {
                $("#_npm").focus();
                toastr.warning('NPM harus diisi')
            } else if(nama == ""){
                $("#_nama").focus();
                toastr.warning('Nama harus diisi')
            } else if (nama == "") {
                $("#_nama").focus();
                toastr.warning('Nama harus diisi')
            } else if (alamat == "") {
                $("#_alamat").focus();
                toastr.warning('Alamat harus diisi')
            } else if (tglLahir == "") {
                $("#_tgl").focus();
                toastr.warning('Tgl harus diisi')
            } else if (email == "") {
                $("#_email").focus();
                toastr.warning('Email harus diisi')
            } else if (jurusan == "") {
                toastr.warning('Pilih Jurusan')
            } else {
                var saveUrl = '@Url.Action("Edit", "Mahasiswa")';
                var IndexUrl = '@Url.Action("Index", "Mahasiswa")';
                var model = {
                    NPM: npm,
                    Nama: nama,
                    JK: jk,
                    IdJurusan: jurusan,
                    Alamat: alamat,
                    TglLahir: formatDate(tglLahir),
                    Email: email,
                };
                $.ajax({
                    type: "POST",
                    url: saveUrl,
                    data: { model: model },
                    success: function (data) {
                        if (data.success) {
                            alert(data.message);
                            window.location.href = IndexUrl;
                        } else {
                            alert(data.message);
                        }
                    }
                });
                }
        }

        function formatDate(date) {
            var d = new Date(date),
            month = '' + (d.getMonth() + 1),
            day = '' + d.getDate(),
            year = d.getFullYear();

            if (month.length < 2) month = '0' + month;
            if (day.length < 2) day = '0' + day;

            return [year, month, day].join('-');
        }
    </script>
}